### ISSUE TITLE
[Feature Request] Add a function to transpose the `tree_map`ed values of a multiple output function

### ISSUE THREAD

**Issue by gRox167** [metaopt/optree#126]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/metaopt/optree/issues) that this hasn't already been reported. (comment there if it has.)

### Motivation

Thanks for all the brilliant work of contributors of this repo!
When we have a multiple output function
```python
def foo(x):
    return x, 2*x
```
And we apply a `tree_map`:
```python
tree_map(foo, [(1,2), 3,4])
```
the output will be a `PyTree` of type `Tuple[int,int]`. However, if we want to get 2 separate trees of the same structure with `PyTree[int]`, we can only do a separate `tree_transpose`
```
    x, x_double = tree_transpose(
        tree_structure([(1,2), 3,4]),
        tree_structure(("*","*")),
        tree_map(foo, [(1,2), 3,4])
    )
```
however, when the returned value have further nested structure, this could be tedious as we need to do another `is_leaf` to determine the leaf node. 

In the situation of separate return value of multiple output function, we know the existing PyTree structure, so it is possible to directly separate the PyTree.

There is a function called `equinox.partition` which could potentially serve this purpose, but it only support splitting pytree into 2 parts, and we still need to write a filter function to determine how to split. 

### Solution

In the best situation, 
```python
def foo(x):
    return x, 2*x
t = [(1,2), 3,4]
x, x_double = tree_map(foo, t, transpose_output_tree_to_outer_tree = True)
```
and for mapping object
```python
def foo(x):
    return {"x":x, "x_double":2*x}
t = [(1,2), 3,4]
x_dict= tree_map(foo, t, transpose_output_tree_to_outer_tree = True)
# x_dict will be {"x":[(1,2), 3,4], "x_double":[(2,4), 6,8]}
```

### Additional context

If you have any idea or suggestion please feel free to comment, I can work on implement this feature if I have a guide on how to do it.

**Comment by gRox167** [comment]
After looking at `tree_map` function, I came up with an idea of separate output into different PyTree. Currently only support tuple output of a function.
```python
def tree_transpose_map(
    func: Callable[..., U],
    tree: PyTree[T],
    *rests: PyTree[S],
    is_leaf: Callable[[T], bool] | None = None,
    none_is_leaf: bool = False,
    namespace: str = "",
) -> Tuple[PyTree, ...]:
    leaves, treespec = _C.flatten(tree, is_leaf, none_is_leaf, namespace)
    flat_args = [leaves] + [treespec.flatten_up_to(r) for r in rests]
    output_tuple = zip(*map(func, *flat_args))
    return tuple(treespec.unflatten(o) for o in output_tuple)
```

**Comment by XuehaiPan** [comment]
Hi @gRox167, thanks for raising this. I think `tre_transpose_map` (or called something else) would be a great feature.

> Currently only support tuple output of a function.

To support functions that return an arbitrary nested structure, we should specify the inner pytree structure.

```python
def tree_transpose_map(
    func: Callable[..., U],
    tree: PyTree[T],
    *rests: PyTree[S],
    inner_treespec: PyTreeSpec | None = None,
    is_leaf: Callable[[T], bool] | None = None,
    none_is_leaf: bool = False,
    namespace: str = '',
) -> PyTree[U]:
    leaves, treespec = tree_flatten(
        tree,
        is_leaf=is_leaf,
        none_is_leaf=none_is_leaf,
        namespace=namespace,
    )
    flat_args = [leaves] + [treespec.flatten_up_to(r) for r in rests]

    outputs = list(map(func, *flat_args))
    if len(outputs) > 0 and inner_treespec is None:
        inner_treespec = tree_structure(
            outputs[0],
            is_leaf=is_leaf,
            none_is_leaf=none_is_leaf,
            namespace=namespace,
        )
    grouped = [inner_treespec.flatten_up_to(o) for o in outputs]
    transposed = zip(*grouped)
    subtrees = map(treespec.unflatten, transposed)
    return inner_treespec.unflatten(subtrees)
```

```python
In [1]: def foo(x):
   ...:     return x, 2 * x
   ...:     

In [2]: tree_transpose_map(foo, [(1, 2), 3, 4])
Out[2]: ([(1, 2), 3, 4], [(2, 4), 6, 8])

In [3]: def bar(x):
   ...:     return {'x': x, 'x_double': 2 * x}
   ...:     

In [4]: tree_transpose_map(bar, [(1, 2), 3, 4])
Out[4]: {'x': [(1, 2), 3, 4], 'x_double': [(2, 4), 6, 8]}
```

**Comment by gRox167** [comment]
Thanks for all your brilliant contribution! `tree_transpose_map` works perfectly fine for my use case. Please let me know if you need any further help such as documentation or examples.
