### ISSUE TITLE
[BUG] incorrect type annotations in optree.dataclasses

### ISSUE THREAD

**Issue by manulari** [metaopt/optree#163]
### Required prerequisites

- [X] I have read the documentation <https://optree.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/metaopt/optree/issues) that this hasn't already been reported. (comment there if it has.)

### What version of OpTree are you using?

0.13.0

### System information

3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0] linux
0.13.0

## optree.dataclass.dataclass
When using `@optree.dataclasses.dataclass` as a decorator (i.e. without the optional cls argument in the initial function call), my type checker (pyright) complains that 'No overloads for "dataclass" match the provided arguments'.

I think the correct way to type the overload would be to completely omit the cls argument here (or alternatively respecify the default argument there (as `cls: None = None`)).  
I.e.: replace
```
@overload  # type: ignore[no-redef]
@dataclass_transform(field_specifiers=(field,))
def dataclass(  # pylint: disable=too-many-arguments
    cls: None,
    *,
    [...]
```
by
```
@overload  # type: ignore[no-redef]
@dataclass_transform(field_specifiers=(field,))
def dataclass(  # pylint: disable=too-many-arguments
    *,
    [...]
```

## optree.dataclasses.field

If I use optree.dataclasses.field, my type checker complains that 'Type "Field[Unknown]" is not assignable to declared type [...]'.
I'm not sure what the correct fix is here, but I noticed that dataclasses.field just leaves out the return type annotation.

<https://github.com/python/typeshed/blob/main/stdlib/dataclasses.pyi> might be helpful as a reference as it provides type stubs for dataclasses.dataclass

### Reproducible example code

The Python snippets:

```python
import optree.dataclasses

@optree.dataclasses.dataclass(namespace="space")
# type error: No overloads for "dataclass" match provided arguments
class SomeClass():
    x : int = optree.dataclasses.field(init=True, pytree_node=False)
    # type error: Type "Field[Unknown]" is not assignable to declared type "int"
```

**Comment by XuehaiPan** [comment]
Hi @manulari, thanks for raising this. Would you mind to submit a PR to resolve this?

**Comment by manulari** [comment]
Hi @XuehaiPan, I'll try, when I get round to it. I'm a bit new to all the tooling surrounding python, and this project seems to use different tooling from what I'm currently using (poetry), so that was a bit of a deterrent.  
But I'll look into it one of the next days.
