### ISSUE TITLE
[Feature Request] Setup Clang-Tidy

### ISSUE THREAD

**Issue by Skylion007** [metaopt/optree#18]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/metaopt/optree/issues) that this hasn't already been reported. (comment there if it has.)

### Motivation

Ensures code quality remains good and catches simple perf mistakes. I see you install it in the makefile but without a clang-tidy config specifying what checks and what the header-filter is, it's easy to miss things.

### Solution

Install clang-tidy preferrably as a Github Action.

**Comment by XuehaiPan** [comment]
@Skylion007 Thanks for the suggestion. We installed the `clang-tidy` but forgot to add the `Makefile` target to enable this check. We will work on this.
