### ISSUE TITLE
[Feature Request] Add flake8-comprehensions linter

### ISSUE THREAD

**Issue by Skylion007** [metaopt/optree#32]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/metaopt/optree/issues) that this hasn't already been reported. (comment there if it has.)

### Motivation

Since this project is speed motivated, it would best best use [flake8-comprehensions](https://github.com/adamchainz/flake8-comprehensions ) to ensure that any list/dict/tuple etc comprehensions. Skimming over the list, of checks it looks like most if not all the best practices are already implemented in this repo, best just to add it though to ensure that future sub-optimal codepaths are not accidentally introduced.

We recently enabled almost all the checks in the latest version of PyTorch.

### Solution

Add flake8-comprehensions plugin

### Alternatives

Do not add it, rely on code review to maintain performance and avoid useless or wasteful comprehensions, builtin calls, etc.

### Additional context

We enabled all the checks in PyTorch anyhow.

**Comment by XuehaiPan** [comment]
Thanks for the advice. I'm going to investigate enabling more flake8 plugins.

**Comment by Skylion007** [comment]
@XuehaiPan FYI, ruff has a pretty good list (and automated fixes for some): https://beta.ruff.rs/docs/rules/

**Comment by XuehaiPan** [comment]
@Skylion007 I opened a new PR #34 to resolve this.
