### ISSUE TITLE
[BUG] Wrong tree path results with custom `is_leaf` condition

### ISSUE THREAD

**Issue by ASEM000** [metaopt/optree#75]
### Required prerequisites

- [X] I have read the documentation <https://optree.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/metaopt/optree/issues) that this hasn't already been reported. (comment there if it has.)

### What version of OpTree are you using?

0.9.1

### System information

```python
import optree as ot
import sys
print(ot.__version__)
# 0.9.1
print(sys.version, sys.platform)
# 3.11.0 | packaged by conda-forge | (main, Jan 14 2023, 12:26:40) [Clang 14.0.6 ] darwin
```

### Problem description

Incorrect path in optree.tree_flatten_with_path.

The following reproduce the problem

### Reproducible example code

```python
import optree as ot
import sys
print(ot.__version__)
# 0.9.1
print(sys.version, sys.platform)
# 3.11.0 | packaged by conda-forge | (main, Jan 14 2023, 12:26:40) [Clang 14.0.6 ] darwin


tree = {"a":1, "b":2, "c": [3,4,5]}

leaves,treedef = ot.tree_flatten(tree, is_leaf=lambda x: False if id(tree) ==id(x) else True)
print(leaves) # one level
# [1, 2, [3, 4, 5]]
print(ot.treespec_paths(treedef)) # one level paths
# [('a',), ('b',), ('c',)]

paths,leaves,treedef = ot.tree_flatten_with_path(tree, is_leaf=lambda x: False if id(tree) ==id(x) else True)
print(leaves) # one level
# [1, 2, [3, 4, 5]]
print(paths) # one level paths
# []
```

### Expected behavior

Expected output is 

```python
# [('a',), ('b',), ('c',)]
```

**Comment by XuehaiPan** [comment]
Hi @ASEM000, thanks for raising this issue! It's a bug that the `paths` are always empty when the `is_leaf` argument is passed. I will open a PR to fix this.
